# Configuration script to Travis-CI
language: python
python:
  - "2.7"
install:
  - make
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=src/soaringcoupons ./bin/test
after_success:
  coveralls
