# Configuration script to Travis-CI
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev --system
  - pip install coveralls
script:
  - ENV_PATH=env.test mypy sklandymas coupons tests
  - black --check manage.py sklandymas coupons tests
  - pytest -v --cov sklandymas --cov coupons --cov-report=html --cov-report=term
after_success:
  coveralls
