# Configuration script to Travis-CI
language: python
python:
  - "2.7"
install:
  - python bootstrap.py
  - ./bin/buildout
  - pip install coverage
  - pip install python-coveralls
script:
  - coverage run --source=src/soaringcoupons --omit='*.html,*.txt' ./bin/test
after_success:
  coveralls
